language: objective-c
osx_image: xcode8.2

script:
  - set -o pipefail
  - xcodebuild -workspace 'Viscosity.xcworkspace' -scheme 'Tests' -configuration Debug -sdk iphonesimulator clean build ARCHS=i386 VALID_ARCHS=i386 ONLY_ACTIVE_ARCH=NO | xcpretty -c

